# permissions for end users to edit nestedapiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedapiserver-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedapiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedapiservers/status
  verbs:
  - get
