#!/usr/bin/env bash

set -ue

minikube_ip=$(minikube ip)
nkas_port=$(kubectl get svc nkas | awk 'NR>1{print $5}' | awk -F'[:/]' '{print $2}')
kubectl get secret nkcm-kubeconfig -o jsonpath='{.data.controller-manager-kubeconfig}' \
    | base64 --decode \
    | sed "/certificate-authority-data/d; s/nkas/$minikube_ip/g; s/6443/$nkas_port/g" | sed '/^    server: .*/a \ \ \ \ insecure-skip-tls-verify: true'
